service: fileManagementServerless
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1


#  environment:
#    variable1: value1

functions:
  fileManagement:
    handler: handler.fileManagement
    events:
      - http: ANY /{proxy+}
      - http: ANY /
configValidationMode: error

